imports:
- path: vpc.jinja
- path: vm-instance.jinja
- path: fw-rules.jinja

resources:
- type: vpc.jinja
  name: backend-vpc
  properties:
    ip_cidr: 10.0.1.0/16
    subnets:
      - region: us-central1
        ip_cidr: 10.0.1.0/24
      - region: us-east1
        ip_cidr: 10.0.2.0/24

- name: backend-vm
  type: vm-instance.jinja
  properties:
    region: us-central1
    zone: us-central1-a
#    network:  https://www.googleapis.com/compute/v1/projects/causal-temple-244304/global/networks/backend-vpc-vpc
#    subnet: https://www.googleapis.com/compute/v1/projects/causal-temple-244304/regions/us-central1/subnetworks/us-central1-0
    network: $(ref.backend-vpc.network)
#    subnet: regions/*REGION/subnetworks/$(ref.backend-vpc.subnet)
    subnet: $(ref.backend-vpc.subnet)
    tags: 
      - allow-ssh

- type: fw-rules.jinja
  name: backend-fw-rule
  properties:
    network: $(ref.backend-vpc.network)
    sourceRanges: 
      - 0.0.0.0/0
    port: 22
    targetTags:
      - allow-ssh