imports:
- path: vpc.jinja
- path: vm-instance.jinja
- path: fw-rules.jinja

resources:
- type: vpc.jinja
  name: backend-vpc
  properties:
    ip_cidr: 10.0.1.0/16
    subnets:
      - region: us-central1
        ip_cidr: 10.0.1.0/24
      - region: us-east1
        ip_cidr: 10.0.2.0/24

- name: backend-vm
  type: vm-instance.jinja
  properties:
    region: us-central1
    zone: us-central1-a
    network: $(ref.backend-vpc.network)
    subnet: $(ref.backend-vpc.vpc-subnets[0])
    tags: 
      - allow-ssh

- type: fw-rules.jinja
  name: backend-fw-rule
  properties:
    network: $(ref.backend-vpc.network)
    sourceRanges: 
      - 0.0.0.0/0
    port: 22
    targetTags:
      - allow-ssh