imports:
- path: vpc.jinja
- path: vm-instance.jinja
- path: fw-rules.jinja

resources:
- type: vpc.jinja
  name: backend-vpc
  properties:
    ip_cidr: 10.0.1.0/16
    subnets:
      - region: us-central1
        ip_cidr: 10.0.1.0/24
      - region: us-east1
        ip_cidr: 10.0.2.0/24

- name: backend-vm
  type: vm-instance.jinja
  properties:
    region: us-central1
    zone: us-central1-a
    network: $(ref.backend-vpc.network)
    subnet: $(ref.backend-vpc.vpc-subnets[0])
    tags: 
      - allow-ssh

- name: front-vm
  type: vm-instance.jinja
  properties:
    region: us-east1
    zone: us-east1-b
    network: $(ref.backend-vpc.network)
    subnet: $(ref.backend-vpc.vpc-subnets[1])
    tags: 
      - allow-icmp

- type: fw-rules.jinja
  name: allow-ssh-fw-rule
  properties:
    network: $(ref.backend-vpc.network)
    sourceRanges: 
      - 0.0.0.0/0
    IPProtocol: tcp
    ports: [ 22 ]
    targetTags:
      - allow-ssh

- type: fw-rules.jinja
  name: allow-icmp-fw-rule
  properties:
    network: $(ref.backend-vpc.network)
    sourceRanges: 
      - 0.0.0.0/0
    IPProtocol: ICMP
    ports: []
    targetTags:
      - allow-icmp